version: '3.7'

services:
  licensing-service:
    image: ostock/licenseserver:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CONFIG_IMPORT= configserver:http://host.docker.internal:8071"
    networks:
      backend:
    depends_on:
      - postgres-database
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres-database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_USER: sa
    volumes:
      - 'dbdata:/var/lib/postgresql/data'


networks:
  backend:
    driver: bridge
volumes:
  dbdata:
